spring.application.name=PlataformaEducativa


# Conf de la base de datos
spring.datasource.url=jdbc:oracle:thin:@201.189.44.89:1521:xe
spring.datasource.username=DCN_S1_user
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Conf de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
